Feat/exercice
PiRB/react-starter-frontend pull request #2
Opened 2022-01-25 15:00 UTC by Lynch-cai

2022-01-25 16:00 UTC, simtaxx requested changes
Delete package-lock.json from your pr.

2022-02-17 13:23 UTC, Lynch-cai commented on spa/src/components/FlipCard/FlipCard.tsx
> +      <FlipCardInner className={isActive ? "active" : ''}>
Failed to compiled avec les deux "?"

2022-02-17 13:49 UTC, Lynch-cai commented on spa/src/components/FlipCard/FlipCard.tsx
> +export const FlipCard: React.FunctionComponent<Props> = (props: Props) => {
Pas compris, genre si je met : ça ne fonctionne pas
export const FlipCard: React.FunctionComponent = ({notTranslated, translated, content}) => {

2022-03-07 10:52 UTC, PiRB approved these changes

2022-03-07 10:52 UTC, PiRB commented
fix conflicts

2022-03-07 10:56 UTC, merged